# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Build STL targeting x64, x86, arm64, arm64ec

variables:
  - template: azure-devops/config.yml

pr:
  drafts: false

stages:
##### Phase 1: Initial Builds #####
  - stage: Code_Format
    dependsOn: []
    displayName: 'Code Format'
    pool:
      name: ${{ variables.x64MediumPoolName }}
      demands: ${{ variables.poolDemands }}
    variables:
    - name: workRoot
      value: '$(x64MediumPoolWorkRoot)'
      readonly: true
    jobs:
      - template: azure-devops/format-validation.yml
