# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Build STL targeting x64, x86, arm64, arm64ec

variables:
  - template: azure-devops/config.yml

pr:
  drafts: false

stages:
  - stage: Build_x64
    dependsOn: []
    displayName: 'Build x64'
    pool:
      name: ${{ variables.x64SlowPoolName }}
      demands: ${{ variables.poolDemands }}
    jobs:
      - template: azure-devops/build-and-test.yml
        parameters:
          hostArch: x64
          targetArch: x64
          targetPlatform: x64
          analyzeBuild: true
          buildBenchmarks: true
          numShards: 1
          configureTesting: false
          runTesting: false

  # This ARM64-native build will detect problems with the ARM64 pool as early as possible.
  # The stage dependencies are structured to optimize the critical path.
  - stage: Build_ARM64_Native
    dependsOn: []
    displayName: 'Build ARM64 (Native)'
    pool:
      name: ${{ variables.arm64PoolName }}
      demands: ${{ variables.poolDemands }}
    jobs:
      - template: azure-devops/build-and-test.yml
        parameters:
          hostArch: arm64
          targetArch: arm64
          targetPlatform: arm64
          analyzeBuild: true
          buildBenchmarks: true
          numShards: 1
          configureTesting: false
          runTesting: false
