# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Build STL targeting x86 and x64, and run extra ASan testing

variables:
  tmpDir: 'D:\Temp'
  buildOutputLocation: 'D:\build'
  # Restrict to "stlasan" test
  testSelection: '-R stlasan'

pr: none
trigger: none

extends:
  template: pool.yml

pipeline:
  stages:
    - stage: Build_And_Test_x64
      displayName: 'Build and Test'
      jobs:
        - template: native-build-test.yml
          parameters:
            targetPlatform: x64
            vsDevCmdArch: amd64
            benchmarkBuildOutputLocationVar: ''
            testSelection: ${{ variables.testSelection }}

    - stage: Build_And_Test_x86
      displayName: 'Build and Test'
      jobs:
        - template: native-build-test.yml
          parameters:
            targetPlatform: x86
            vsDevCmdArch: x86
            benchmarkBuildOutputLocationVar: ''
            testSelection: ${{ variables.testSelection }}

    # no coverage for ARM and ARM64
