# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Build STL targeting x64, x86, and arm64, then run extra ASan testing

variables:
  - template: config.yml

trigger: none

schedules:
- cron: '0 2 * * *'
  displayName: ASan-Daily-CI
  branches:
    include:
    - main

stages:
  - stage: Test_x64_ASan
    displayName: 'Test x64 ASan'
    dependsOn: []
    pool:
      name: ${{ variables.poolName }}
      demands: ${{ variables.poolDemands }}
    jobs:
      - template: build-and-test.yml
        parameters:
          hostArch: x64
          targetArch: x64
          targetPlatform: x64
          asanBuild: true
          testTargets: STL-ASan-CI

  - stage: Test_x86_ASan
    displayName: 'Test x86 ASan'
    dependsOn: []
    pool:
      name: ${{ variables.poolName }}
      demands: ${{ variables.poolDemands }}
    jobs:
      - template: build-and-test.yml
        parameters:
          hostArch: x86
          targetArch: x86
          targetPlatform: x86
          asanBuild: true
          testTargets: STL-ASan-CI

  - stage: Test_ARM64_ASan
    displayName: 'Test ARM64 ASan'
    dependsOn: []
    pool:
      name: ${{ variables.arm64PoolName }}
      demands: ${{ variables.poolDemands }}
    jobs:
      - template: build-and-test.yml
        parameters:
          hostArch: arm64
          targetArch: arm64
          targetPlatform: arm64
          asanBuild: true
          testTargets: STL-ASan-CI
