# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Build STL targeting x86 and x64, and run extra ASan testing

variables:
  tmpDir: 'D:\Temp'
  buildOutputLocation: 'D:\build'
  # We do not want to build the benchmarks in this pipeline
  benchmarkBuildOutputLocation: ''
  benchmarkBuildOutputLocationVar: ''
  # Restrict to "stlasan" test
  testSelection: '-R stlasan'

pool:
  name: 'StlBuild-2023-09-14T1251-Pool'
  demands: EnableSpotVM -equals true

pr:
  drafts: false

stages:
  - stage: Code_Format
    displayName: 'Code Format'
    jobs:
      - template: format-validation.yml

  - stage: Build_And_Test_x64
    dependsOn: Code_Format
    displayName: 'Build and Test'
    jobs:
      - template: native-build-test.yml
        parameters:
          targetPlatform: x64
          vsDevCmdArch: amd64
          benchmarkBuildOutputLocationVar: ${{ variables.benchmarkBuildOutputLocationVar }}
          testSelection: ${{ variables.testSelection }}

  - stage: Build_And_Test_x86
    dependsOn: Build_And_Test_x64
    displayName: 'Build and Test'
    jobs:
      - template: native-build-test.yml
        parameters:
          targetPlatform: x86
          vsDevCmdArch: x86
          benchmarkBuildOutputLocationVar: ${{ variables.benchmarkBuildOutputLocationVar }}
          testSelection: ${{ variables.testSelection }}

  # no coverage for ARM and ARM64
