# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Build STL targeting x86 and x64, and run extra ASan testing

variables:
  - template: config.yml

trigger: none

schedules:
- cron: '0 2 * * *'
  displayName: ASan-Daily-CI
  branches:
    include:
    - main

stages:
  - stage: Build_And_Test_x64
    displayName: 'Build and Test x64'
    pool:
      name: ${{ variables.poolName }}
      demands: ${{ variables.poolDemands }}
    jobs:
      - template: build-and-test.yml
        parameters:
          hostArch: x64
          targetArch: x64
          asanBuild: true
          ctestOptions: '--tests-regex stlasan'

  - stage: Build_And_Test_x86
    displayName: 'Build and Test x86'
    dependsOn: []
    pool:
      name: ${{ variables.poolName }}
      demands: ${{ variables.poolDemands }}
    jobs:
      - template: build-and-test.yml
        parameters:
          hostArch: x86
          targetArch: x86
          asanBuild: true
          ctestOptions: '--tests-regex stlasan'

  # no coverage for ARM and ARM64
