# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

parameters:
- name: hostArch
  type: string
- name: targetArch
  type: string
- name: asanBuild
  type: boolean
  default: false
- name: buildBenchmarks
  type: boolean
  default: true
- name: cmakeAdditionalFlags
  type: string
  default: ''
- name: ctestOptions
  type: string
  default: '--exclude-regex stlasan'
- name: numShards
  type: number
  default: 8
jobs:
- job: '${{ parameters.targetArch }}'
  strategy:
    parallel: ${{ parameters.numShards }}
  timeoutInMinutes: 30
  steps:
  - script: |
      if exist "$(tmpDir)" (rmdir /S /Q $(tmpDir))
      mkdir $(tmpDir)
    displayName: 'Setup TMP Directory'

  - template: checkout-sources.yml
  - template: cmake-configure-build.yml
    parameters:
      hostArch: ${{ parameters.hostArch }}
      targetArch: ${{ parameters.targetArch }}
      asanBuild: ${{ parameters.asanBuild }}
      buildBenchmarks: ${{ parameters.buildBenchmarks }}
      cmakeAdditionalFlags: ${{ parameters.cmakeAdditionalFlags }}
  - template: run-tests.yml
    parameters:
      hostArch: ${{ parameters.hostArch }}
      targetArch: ${{ parameters.targetArch }}
      ctestOptions: ${{ parameters.ctestOptions }}
