# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Common configuration used by both pipelines

variables:
- name: x64SlowPoolName
  value: 'Stl-2026-06-25T1103-x64-Fasv6-Pool'
  readonly: true
- name: x64FastPoolName
  value: 'Stl-2026-06-25T1103-x64-Fasv7-Pool'
  readonly: true
- name: arm64PoolName
  value: 'Stl-2026-07-13T1338-arm64-Dpdsv6-Pool'
  readonly: true
- name: poolDemands
  value: 'EnableSpotVM -equals false'
  readonly: true
- name: launchVsDevShell
  value: 'C:\Program Files\Microsoft Visual Studio\18\Insiders\Common7\Tools\Launch-VsDevShell.ps1'
  readonly: true
- name: tmpDir
  ${{ if eq(parameters.hostArch, 'arm64') }}:
    value: 'E:\stlTemp'
  ${{ else }}:
    value: 'C:\stlTemp'
  readonly: true
- name: buildOutputLocation
  ${{ if eq(parameters.hostArch, 'arm64') }}:
    value: 'E:\stlBuild'
  ${{ else }}:
    value: 'C:\stlBuild'
  readonly: true
- name: benchmarkBuildOutputLocation
  ${{ if eq(parameters.hostArch, 'arm64') }}:
    value: 'E:\stlBenchmark'
  ${{ else }}:
    value: 'C:\stlBenchmark'
  readonly: true
- name: validationBuildOutputLocation
  ${{ if eq(parameters.hostArch, 'arm64') }}:
    value: 'E:\stlValidation'
  ${{ else }}:
    value: 'C:\stlValidation'
  readonly: true
- name: Codeql.SkipTaskAutoInjection
  value: true
  readonly: true
- name: skipComponentGovernanceDetection
  value: true
  readonly: true
