# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

parameters:
- name: hostArch
  type: string
  default: amd64
- name: targetPlatform
  type: string
- name: vsDevCmdArch
  type: string
- name: buildBenchmarks
  type: boolean
  default: true
- name: numShards
  type: number
  default: 8
jobs:
- job: '${{ parameters.targetPlatform }}'
  strategy:
    parallel: ${{ parameters.numShards }}
  timeoutInMinutes: 30
  steps:
  - script: |
      if exist "$(tmpDir)" (rmdir /S /Q $(tmpDir))
      mkdir $(tmpDir)
    displayName: 'Setup TMP Directory'

  - template: checkout-sources.yml
  - template: cmake-configure-build.yml
    parameters:
      targetPlatform: ${{ parameters.targetPlatform }}
      hostArch: ${{ parameters.hostArch }}
      targetArch: ${{ parameters.vsDevCmdArch }}
      cmakeAdditionalFlags: '-DTESTS_BUILD_ONLY=ON'
      buildBenchmarks: ${{ parameters.buildBenchmarks }}
  - template: run-tests.yml
    parameters:
      hostArch: ${{ parameters.hostArch }}
      targetPlatform: ${{ parameters.targetPlatform }}
      targetArch: ${{ parameters.vsDevCmdArch }}
      displayName: 'Build Tests'
      # Exclude "stlasan" test (we don't yet support ASAN on ARM or ARM64)
      testSelection: '-E stlasan'
