# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# run the `validator` tool, and ensure code is properly clang-formatted

jobs:
- job: Code_Format_Validation
  timeoutInMinutes: 5
  displayName: 'Validation'
  steps:
    - script: |
        if exist "$(tmpDir)" (
          rmdir /S /Q $(tmpDir)
        )
        mkdir $(tmpDir)
      displayName: 'Setup TMP Directory'
    - checkout: self
      clean: true
      submodules: false
    - script: |
        cd $(Build.SourcesDirectory)
        git clean --quiet -x -d -f -f
      displayName: 'Clean after checkout'
    - script: |
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Preview\Common7\Tools\VsDevCmd.bat" ^
          -host_arch=amd64 -arch=amd64 -no_logo
        cmake -G Ninja -S $(Build.SourcesDirectory)/tools -B $(tmpDir)/format-validate-build
        cmake --build $(tmpDir)/format-validate-build
      displayName: 'Build format and validation'
      timeoutInMinutes: 5
      env: { TMP: $(tmpDir), TEMP: $(tmpDir) }
    - script: |
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Preview\Common7\Tools\VsDevCmd.bat" ^
          -host_arch=amd64 -arch=amd64 -no_logo
        cmake --build $(tmpDir)/format-validate-build --target run-format
      displayName: 'clang-format Files'
      timeoutInMinutes: 5
      env: { TMP: $(tmpDir), TEMP: $(tmpDir) }
    - script: |
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Preview\Common7\Tools\VsDevCmd.bat" ^
          -host_arch=amd64 -arch=amd64 -no_logo
        cmake --build $(tmpDir)/format-validate-build --target run-validate
      displayName: 'Validate Files'
      timeoutInMinutes: 2
      env: { TMP: $(tmpDir), TEMP: $(tmpDir) }
    - task: Powershell@2
      displayName: 'Create Diff'
      inputs:
        filePath: azure-devops/create-prdiff.ps1
        pwsh: false
      condition: succeededOrFailed()
      env: { TMP: $(tmpDir), TEMP: $(tmpDir) }
