# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

parameters:
- name: hostArch
  type: string
- name: targetArch
  type: string
- name: buildBenchmarks
  type: boolean
  default: true
- name: asanBuild
  type: boolean
  default: false
- name: numShards
  type: number
  default: 8
  # Parameters to pass to ctest to select the test(s) to run
- name: testSelection
  type: string
  # Exclude "stlasan" test by default
  default: '-E stlasan'
jobs:
- job: '${{ parameters.targetArch }}'
  strategy:
    parallel: ${{ parameters.numShards }}
  timeoutInMinutes: 30
  steps:
  - script: |
      if exist "$(tmpDir)" (rmdir /S /Q $(tmpDir))
      mkdir $(tmpDir)
    displayName: 'Setup TMP Directory'

  - template: checkout-sources.yml
  - template: cmake-configure-build.yml
    parameters:
      hostArch: ${{ parameters.hostArch }}
      targetArch: ${{ parameters.targetArch }}
      buildBenchmarks: ${{ parameters.buildBenchmarks }}
      asanBuild: ${{ parameters.asanBuild }}
  - template: run-tests.yml
    parameters:
      hostArch: ${{ parameters.hostArch }}
      targetArch: ${{ parameters.targetArch }}
      testSelection: ${{ parameters.testSelection }}
