# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

jobs:
- job: ${{ parameters.targetPlatform }}
  timeoutInMinutes: 360
  pool:
    name: $(agentPool)

  variables:
    vcpkgLocation: '$(Build.SourcesDirectory)/vcpkg'
    buildOutputLocation: 'D:/build'
    litFlags: '-j$[testParallelism];--xunit-xml-output $[buildOutputLocation]/${{ parameters.targetPlatform }}/test-results.xml;--timeout 240;--shuffle'
  steps:
    - script: |
        if exist "$(tmpDir)" (
          rmdir /S /Q $(tmpDir)
        )
        mkdir $(tmpDir)
      displayName: 'Setup TMP Directory'
    - checkout: self
      clean: true
      submodules: true
    - task: Cache@2
      displayName: Cache vcpkg
      timeoutInMinutes: 10
      inputs:
        key: '"${{ parameters.targetPlatform }}" | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "2020-03-01.01"'
        path: '$(vcpkgLocation)/installed'
        cacheHitVar: CACHE_RESTORED
    - task: run-vcpkg@0
      displayName: 'Run vcpkg to Install boost-build'
      condition: and(ne(variables.CACHE_RESTORED, 'true'), contains('${{ parameters.targetPlatform }}', 'arm'))
      timeoutInMinutes: 10
      inputs:
        vcpkgArguments: 'boost-build'
        vcpkgDirectory: '$(vcpkgLocation)'
        vcpkgTriplet: 'x86-windows'
      env: { TMP: $(tmpDir), TEMP: $(tmpDir) }
    - task: run-vcpkg@0
      displayName: 'Run vcpkg'
      timeoutInMinutes: 10
      inputs:
        vcpkgArguments: 'boost-math'
        vcpkgDirectory: '$(vcpkgLocation)'
        vcpkgTriplet: '${{ parameters.targetPlatform }}-windows'
      env: { TMP: $(tmpDir), TEMP: $(tmpDir) }
    - task: PowerShell@2
      displayName: 'Get Test Parallelism'
      timeoutInMinutes: 2
      inputs:
        targetType: inline
        script: |
          $testParallelism = $env:NUMBER_OF_PROCESSORS - 2
          Write-Output "##vso[task.setvariable variable=testParallelism;]$testParallelism"
    - task: run-cmake@0
      displayName: 'Build the STL'
      timeoutInMinutes: 10
      inputs:
        cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
        cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
        buildDirectory: $(buildOutputLocation)/${{ parameters.targetPlatform }}
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: |
          -G Ninja -DADDITIONAL_LIT_FLAGS="$(litFlags)"
      env: { TMP: $(tmpDir), TEMP: $(tmpDir) }
    - task: CmdLine@2
      displayName: 'Run Tests'
      timeoutInMinutes: 120
      condition: in('${{ parameters.targetPlatform }}', 'x64', 'x86')
      inputs:
        workingDirectory: $(buildOutputLocation)/${{ parameters.targetPlatform }}
        script: |
          call "%PROGRAMFILES(X86)%\Microsoft Visual Studio\2019\Preview\Common7\Tools\VsDevCmd.bat" ^
          -host_arch=${{ parameters.vsDevCmdArch }} -arch=${{ parameters.vsDevCmdArch }} -no_logo
          ctest -V
      env: { TMP: $(tmpDir), TEMP: $(tmpDir) }
    - task: PublishTestResults@2
      displayName: 'Publish Tests'
      timeoutInMinutes: 10
      condition: in('${{ parameters.targetPlatform }}', 'x64', 'x86')
      inputs:
        searchFolder: $(buildOutputLocation)/${{ parameters.targetPlatform }}
        testResultsFormat: JUnit
        testResultsFiles: '**/test-results.xml'
        testRunTitle: 'test-${{ parameters.targetPlatform }}'
