# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
parameters:
  targetPlatform: 'x64'

jobs:
- job: ${{ parameters.targetPlatform }}
  pool:
    name: STL

  variables:
    vcpkgLocation: '$(Build.SourcesDirectory)/vcpkg'
    vcpkgResponseFile: $(Build.SourcesDirectory)/vcpkg_windows.txt
  steps:
    - checkout: self
      submodules: recursive
    - task: PowerShell@2
      displayName: 'Install MSVC Preview'
      # on "Hosted" agents only:
      condition: or(contains(variables['Agent.Name'], 'Azure Pipelines'), contains(variables['Agent.Name'], 'Hosted Agent'))
      inputs:
        targetType: filePath
        filePath: $(Build.SourcesDirectory)/azure-devops/install_msvc_preview.ps1
    - task: CacheBeta@0
      displayName: Cache vcpkg
      inputs:
        key: $(vcpkgResponseFile) | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD
        path: '$(vcpkgLocation)'
    - task: run-vcpkg@0
      displayName: 'Run vcpkg to Install boost-build'
      inputs:
        vcpkgArguments: 'boost-build:x86-windows'
        vcpkgDirectory: '$(vcpkgLocation)'
    - task: run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgArguments: '@$(vcpkgResponseFile)'
        vcpkgDirectory: '$(vcpkgLocation)'
        vcpkgTriplet: ${{ parameters.targetPlatform }}-windows
    - task: run-cmake@0
      displayName: 'Build Support Tools'
      enabled: true
      condition: eq('${{ parameters.targetPlatform }}', 'x64')
      inputs:
        cmakeListsTxtPath: 'tools/CMakeSettings.json'
        useVcpkgToolchainFile: true
        configurationRegexFilter: '.*x64-Release.*'
        buildDirectory: $(Build.ArtifactStagingDirectory)/tools
    - task: BatchScript@1
      displayName: 'Enforce clang-format'
      condition: eq('${{ parameters.targetPlatform }}', 'x64')
      inputs:
        filename: 'azure-devops/enforce-clang-format.cmd'
        failOnStandardError: true
        arguments: '$(Build.ArtifactStagingDirectory)/tools/parallelize/parallelize.exe'
    - task: run-cmake@0
      displayName: 'Build the STL'
      enabled: true
      inputs:
        cmakeListsTxtPath: 'CMakeSettings.json'
        useVcpkgToolchainFile: true
        configurationRegexFilter: '.*${{ parameters.targetPlatform }}.*'
        buildDirectory: $(Build.ArtifactStagingDirectory)/${{ parameters.targetPlatform }}
