# Build STL targeting x86, x64, arm, arm64

parameters:
  pool: {}

jobs:
  - template: run_job_docker.yml
    parameters:
      targetPlatform: x86
      pool: ${{ parameters.pool }}

  - template: run_job_docker.yml
    parameters:
      targetPlatform: x64
      pool: ${{ parameters.pool }}

  - template: run_job_docker.yml
    parameters:
      targetPlatform: arm
      pool: ${{ parameters.pool }}

  - template: run_job_docker.yml
    parameters:
      targetPlatform: arm64
      pool: ${{ parameters.pool }}
