# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Compile TypeScript
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '>=26.3.1'
      - name: Install Packages
        run: |
          npm ci
      - name: Compile gather_stats.mts
        run: |
          npx tsc --noEmit -p src_gather/tsconfig.json
      - name: Compile status_chart.mts
        run: |
          npx tsc -p src/tsconfig.json
